{
 "title": "Prometheus Wrapper Demo",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Start Time",
   "type": "stat",
   "description": "Start time of the last batch run",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fs_etl_start_timestamp_seconds{batch=\"eft\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Size (txn count : info)",
   "type": "stat",
   "description": "Number of records for the batch in process",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txn_count{batch=\"eft\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Run Time",
   "type": "stat",
   "description": "Batch run in seconds",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fs_etl_competion_timestamp_seconds{batch=\"eft\"}-fs_etl_start_timestamp_seconds{batch=\"eft\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completion Time",
   "type": "stat",
   "description": "Completion time of the last batch run",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fs_etl_competion_timestamp_seconds{batch=\"eft\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Record: (fs_etl_operations_total)",
   "type": "stat",
   "description": "Current records processed",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fs_etl_operations_total{batch=\"eft\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "api duration (fs_api_duration_seconds) (histogram)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.099, sum by(le) (rate(fs_api_duration_seconds_bucket{batch=\"eft\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.090, sum by(le) (rate(fs_api_duration_seconds_bucket{batch=\"eft\"}[1m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.050, sum by(le) (rate(fs_api_duration_seconds_bucket{batch=\"eft\"}[1m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.010, sum by(le) (rate(fs_api_duration_seconds_bucket{batch=\"eft\"}[1m])))",
     "legendFormat": "P10"
    }
   ]
  },
  {
   "title": "fs_etl_operations_total (Counter) Rate 1M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(fs_etl_operations_total{batch=\"eft\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}